export const tasks = [
    {
        id: 0,
        title: "Benchmark",
        description: "",
        endDate: '2021-11-16',
        users: [2],
        categories: [2, 3],        
        attached: [0, 1],
        comments: [0],
        pic: "",
        section: 0,
    },
    {
        id: 1,
        title: "Books",
        description: "",
        endDate: '2021-11-17',
        users: [5, 6],
        categories: [0, 3, 4],        
        attached: [2, 3, 4],
        comments: [1, 2],
        pic: "src/Assets/Img/Cards/books.png",
        section: 0,
    },
    {
        id: 2,
        title: "Landing page",
        description: "",
        endDate: '2021-12-01',
        users: [3, 0, 1],
        categories: [0, 2, 3],        
        attached: [2],
        comments: [],
        pic: "",
        section: 0,
    },
    {
        id: 3,
        title: "Conceptboard",
        description: "",
        endDate: '2021-12-01',
        users: [0, 2],
        categories: [0],        
        attached: [1],
        comments: [3],
        pic: "",  
        section: 1,
    },
    {
        id: 4,
        title: "UX Experience",
        description: "",
        endDate: '2021-12-25',
        users: [6, 2],
        categories: [0, 2, 3, 4],        
        attached: [2],
        comments: [],
        pic: "src/Assets/Img/Cards/ux.jpg",
        section: 1,
    },
    {
        id: 5,
        title: "Information",
        description: "",
        endDate: '2022-01-06',
        users: [2],
        categories: [1, 2, 3, 4],        
        attached: [2],
        comments: [],
        pic: "src/Assets/Img/Cards/TeC5pm55CkE.png",   
        section: 2,
    },
    {
        id: 6,
        title: "Moodboard",
        description: "",
        endDate: '2022-01-22',
        users: [3, 1],
        categories: [0, 2, 4],        
        attached: [],
        comments: [],
        pic: "",   
        section: 2,
    },
    {
        id: 7,
        title: "Cardsorting",
        description: "",
        endDate: '2022-01-31',
        users: [0, 4],
        categories: [0, 1, 3, 4],        
        attached: [1],
        comments: [],
        pic: "src/Assets/Img/Cards/cardsorting.png",  
        section: 3,
    },    
]